using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UrlShortener.Core.Models
{
	/// <summary>
	/// This models servers as DomainModel, ViewModel and DataModel in this application
	/// for the sake of simplicity given the fact that the mentioned models 
	/// had no or slight differences in terms of strucure.
	/// </summary>
	public class Link
	{
		/// <summary>
		/// Gets or sets the identifier of the entity which is Database AutoGenerated.
		/// </summary>
		/// <value>
		/// The identifier.
		/// </value>
		[Key]
		public int Id { get; set; }

		/// <summary>
		/// Gets or sets the short URL which is a calculated property and is not stored in database.
		/// </summary>
		/// <value>
		/// The calculated short URL.
		/// </value>
		[NotMapped]
		[Display(Name = "Short Url")]
		public string ShortUrl { get; set; }

		/// <summary>
		/// Gets or sets the long URL to be shortened.
		/// </summary>
		/// <value>
		/// The long URL.
		/// </value>
		[Required(AllowEmptyStrings = false, ErrorMessage = "Long url must have a value")]
		[MaxLength(2000, ErrorMessage = "Url must be 2000 characters or less")]
		[Display(Name = "Long Url")]
		public string LongUrl { get; set; }

		/// <summary>
		/// Gets or sets the creation datetime of the record in system.
		/// </summary>
		/// <value>
		/// The created date.
		/// </value>
		[Display(Name = "Create Date")]
		public DateTime CreatedDate { get; set; }

		/// <summary>
		/// Gets or sets the number of times this url has been accessed using the shortUrl link.
		/// </summary>
		/// <value>
		/// The clicks.
		/// </value>
		[Display(Name = "Number of Clicks")]
		public int Clicks { get; set; }
	}
}